# Generated by Django 2.1 on 2020-04-14 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pickup_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
