# Generated by Django 3.0.5 on 2020-04-27 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0007_frequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fgroup2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('time1', models.TimeField()),
                ('gender1', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('pickup_from1', models.CharField(max_length=100)),
                ('passengers2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('time2', models.TimeField()),
                ('gender2', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('pickup_from2', models.CharField(max_length=100)),
                ('passengers3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('date', models.DateField()),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
