# Generated by Django 3.0.5 on 2020-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0008_fgroup2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgroup2',
            name='created_by1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='fgroup2',
            name='created_by2',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
