# Generated by Django 3.0.5 on 2020-04-27 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0009_auto_20200427_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgroup2',
            name='passengers3',
        ),
        migrations.AddField(
            model_name='fgroup2',
            name='total_passengers',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
