# Generated by Django 3.0.5 on 2020-05-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0012_fgroup3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='booked',
        ),
    ]
