# Generated by Django 3.0.5 on 2020-05-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0013_auto_20200505_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grequest3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=100)),
                ('to1', models.CharField(max_length=100)),
                ('to2', models.CharField(max_length=100)),
                ('to3', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('booking_id', models.IntegerField(default=0)),
            ],
        ),
    ]
