# Generated by Django 2.1 on 2020-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
